name: Docker Compose Up on Green Checkmark

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  deploy:
    if: github.event.head_commit.author.name != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build Container
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cont:latest .

      - name: Docker Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cont:latest

      - name: Deploy to VPS (via SSH)
        run: |
          sshpass -p "${{ secrets.ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            echo ${{ secrets.ROOT_PASSWORD }} | sudo -S docker pull ${{ secrets.DOCKER_USERNAME }}/cont:latest
            echo ${{ secrets.ROOT_PASSWORD }} | sudo -S minikube delete

            echo ${{ secrets.ROOT_PASSWORD }} | sudo -S minikube start --driver=docker --memory=2048mb --force
            echo ${{ secrets.ROOT_PASSWORD }} | sudo -S kubectl create deployment cont --image=${{ secrets.DOCKER_USERNAME }}/cont:latest
            
            echo ${{ secrets.ROOT_PASSWORD }} | sudo -S kubectl expose deployment cont --port=3000 --type=NodePort
            echo ${{ secrets.ROOT_PASSWORD }} | sudo -S kubectl rollout status deployment cont
            echo ${{ secrets.ROOT_PASSWORD }} | sudo -S kubectl port-forward --address 0.0.0.0 service/cont 3000:3000 &
          EOF
